# Generated by Django 3.1.2 on 2020-10-22 10:39

from django.db import migrations, models
import django.db.models.deletion
import users.models
import users.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('sex', models.CharField(blank=True, choices=[('nieznana', 'nieznana'), ('mężczyzna', 'mężczyzna'), ('kobieta', 'kobieta')], max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='profile_image/default.png', storage=users.storage.OverwriteStorage(), upload_to=users.models.get_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Dodatkowe informacje o użytkownikach',
            },
        ),
        migrations.CreateModel(
            name='user_survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=0, max_digits=3)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bicep', models.DecimalField(decimal_places=2, max_digits=4)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hips', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stress', models.CharField(max_length=20)),
                ('survey_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile')),
            ],
            options={
                'verbose_name_plural': 'Ankiety',
            },
        ),
    ]
