# Generated by Django 3.1.2 on 2020-10-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('nieokreślona', 'nieokreślona'), ('mężczyzna', 'mężczyzna'), ('kobieta', 'kobieta')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_survey',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='users.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_survey',
            name='waist',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
