# Generated by Django 3.1.2 on 2020-10-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201018_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_survey',
            name='survey_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
