# Generated by Django 3.1.2 on 2020-10-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_survey_survey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_survey',
            name='survey_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
