# Generated by Django 3.1.2 on 2020-10-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201018_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterModelOptions(
            name='user_survey',
            options={'verbose_name_plural': 'Ankiety'},
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='username',
        ),
    ]
