# Generated by Django 3.1.2 on 2020-10-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201019_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name_plural': 'Dodatkowe informacje o użytkownikach'},
        ),
    ]
