# Generated by Django 3.1.2 on 2020-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
