# Generated by Django 3.1.2 on 2020-10-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201021_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='profile_image/default.png', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('nieznana', 'nieznana'), ('mężczyzna', 'mężczyzna'), ('kobieta', 'kobieta')], max_length=10, null=True),
        ),
    ]
