# Generated by Django 3.1.2 on 2020-10-21 22:18

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201021_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='profile_image/default.png', upload_to=users.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='user_survey',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile'),
        ),
    ]
