# Generated by Django 3.1.2 on 2020-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='random_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='random_photos/default.png', upload_to='random_photos')),
            ],
            options={
                'verbose_name_plural': 'Zdjęcia',
            },
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name_plural': 'Ciekawostki'},
        ),
        migrations.AlterField(
            model_name='fact',
            name='text',
            field=models.TextField(),
        ),
    ]
