# Generated by Django 3.1.2 on 2020-10-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201025_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='random_photos',
        ),
    ]
